name: tf-dev
channels:
- anaconda
- conda-forge
- defaults
 
dependencies:
 - python=3.8
 - numpy
 - matplotlib
 - pandas
 - notebook
 - nb_conda_kernels
 - seaborn
 - yfinance
 - joblib
 - pandas-datareader
 - jupyter_contrib_nbextensions